delta:
  catalog: "spotify_graph"     # Unity Catalog catalog name
  schema: "bronze"             # schema within the catalog

neo4j:
  uri_secret_scope: "neo4j"
  uri_secret_key: "uri"
  username_secret_scope: "neo4j"
  username_secret_key: "username"
  password_secret_scope: "neo4j"
  password_secret_key: "password"
  database: "neo4j"
